/**
 * BLD-560 Epic B - Task B5 -- tool-description integrity over the 11-tool inventory.
 * Proves the regenerated KNOWN_GOOD_TOOL_HASH matches the live (post-fork + enforced)
 * inventory, that tampering with any description aborts, and that the hash is a real
 * SHA256 (64 hex) -- regenerated by scripts/regen-integrity-hash.mjs, never hand-typed.
 */
import { test } from "node:test";
import assert from "node:assert/strict";
import { getToolDefinitions } from "../tools/index.js";
import {
  computeToolDescriptionHash, verifyToolDescriptionHash, KNOWN_GOOD_TOOL_HASH,
} from "../integrity.js";

function defs() { return getToolDefinitions(["production"], "production"); }

test("KNOWN_GOOD_TOOL_HASH is a 64-char hex SHA256", () => {
  assert.match(KNOWN_GOOD_TOOL_HASH, /^[0-9a-f]{64}$/);
});

test("inventory is the 11-tool set (8 base + 3 enforced), delete_document absent", () => {
  const names = defs().map(d => d.name).sort();
  assert.equal(names.length, 11);
  for (const n of ["record_override", "confirm_override", "retract_override"]) assert.ok(names.includes(n));
  assert.ok(!names.includes("delete_document"));
});

test("regenerated hash matches the live inventory (GREEN)", () => {
  assert.equal(computeToolDescriptionHash(defs()), KNOWN_GOOD_TOOL_HASH);
  assert.equal(verifyToolDescriptionHash(defs()), true);
});

test("the stale 8-tool hash would NOT verify the new inventory (RED is real)", () => {
  const STALE = "a49a5d404a0fd8b781b8fe01ed391d5dbc7d36f97acb093a73792d2895e79619";
  assert.notEqual(KNOWN_GOOD_TOOL_HASH, STALE);
});

test("tampering with any tool description aborts startup", () => {
  const tampered = defs().map(d => ({ ...d }));
  tampered[0] = { ...tampered[0], description: tampered[0].description + " x" };
  assert.throws(() => verifyToolDescriptionHash(tampered), (e) => /hash mismatch/.test(e.message));
});
