/**
 * ZAPPHIRE Hermes MCP -- Tool Description Integrity Verification
 * Fork: jazzahupwork-boop/mcp-firestore-server v2.0.1-zapphire1
 * Spec: spec-hermes-mcp-connector-architecture-v1 V1.2 -- Invariant 9
 *
 * Defends against tool description tampering (R15/R16/R17 in spec red team).
 *
 * HASH DERIVATION PROCEDURE (SC-R-01 compliance):
 * Hash is computed from SOURCE CODE (static description strings), NOT from
 * a running server instance. The hash below was derived at commit time by:
 *
 *   1. Collecting all tool definitions from src/tools/ (12 tools: 8 base + 3
 *      enforced crm_overrides writers (BLD-560 Epic B) + resolve_timestamp
 *      (task-MCP-MERGE, BLD-652))
 *   2. Sorting entries by tool name (alphabetical)
 *   3. Concatenating: name + description for each sorted entry
 *   4. SHA256(concatenated_string, encoding='utf-8')
 *
 * Tool inventory at hash derivation (sorted):
 *   batch_get         -- "Fetch multiple documents by ID..."
 *   confirm_override  -- "Client confirm-back for a GATED crm_overrides override..."
 *   count_documents   -- "Count documents in a collection..."
 *   create_document   -- "Create a new document..."
 *   get_document      -- "Get a specific document by ID..." (BLD-501 _meta note)
 *   list_collections  -- "List collections. Lists top-level..."
 *   query_collection  -- "Query a Firestore collection..." (BLD-501 default projection + _meta)
 *   query_with_where  -- "Query a collection with where conditions..." (BLD-501 default projection + _meta)
 *   record_override   -- "Record a client-directed crm_overrides override..."
 *   resolve_timestamp -- "Returns the current date/time as an ISO 8601 timestamp..."
 *   retract_override  -- "Retract an active or pending crm_overrides override..."
 *   update_document   -- "Update an existing document..."
 *
 * NOTE: delete_document was REMOVED in this fork (D2 Director decision).
 * task-MCP-MERGE (BLD-652): override engine (f2ba66e7, 11 tools) merged with the FM-3
 * projection stack overlay (master) plus the new resolve_timestamp tool (12th tool);
 * this hash was regenerated by scripts/regen-integrity-hash.mjs over the 12-tool
 * inventory. If any tool description changes, recompute via that script -- never hand-edit.
 *
 * Verification script: zapphireIaC/scripts/hermes/verify-mcp-descriptions
 */

import { createHash } from 'crypto';

/**
 * Known-good SHA256 of sorted tool (name + description) concatenation.
 * Derived from source at this commit. Replaces on any tool description change.
 *
 * Commit: task-MCP-MERGE (BLD-652) -- resealed for the 12-tool merged inventory.
 * Prior value (11-tool override-engine base, f2ba66e7): aa1f78f7...59e041.
 */
export const KNOWN_GOOD_TOOL_HASH =
  '46e43ed8d4e69b845562ef42f0dbcbac7edf4cbf9edfd61ca3c4de0b729cd822';

/**
 * Compute SHA256 of sorted tool (name + description) concatenation.
 *
 * @param {Array<{name: string, description: string}>} toolDefinitions
 * @returns {string} hex digest
 */
export function computeToolDescriptionHash(toolDefinitions) {
  const sorted = [...toolDefinitions]
    .sort((a, b) => a.name.localeCompare(b.name));
  const input = sorted
    .map(t => t.name + t.description)
    .join('');
  return createHash('sha256').update(input, 'utf8').digest('hex');
}

/**
 * Verify tool descriptions match the known-good hash.
 * Throws if mismatch -- server startup aborts.
 *
 * Called after getToolDefinitions() in startServer().
 * Provides defence against tool description tampering between install and start.
 *
 * @param {Array<{name: string, description: string}>} toolDefinitions
 * @throws {Error} on hash mismatch
 */
export function verifyToolDescriptionHash(toolDefinitions) {
  const computed = computeToolDescriptionHash(toolDefinitions);
  if (computed !== KNOWN_GOOD_TOOL_HASH) {
    throw new Error(
      `[INTEGRITY] Tool description hash mismatch detected at startup. ` +
      `Expected: ${KNOWN_GOOD_TOOL_HASH}. ` +
      `Computed:  ${computed}. ` +
      `This indicates tool descriptions have been modified after the ` +
      `integrity hash was set. Halting -- do not operate a compromised server.`
    );
  }
  console.error('[INTEGRITY] Tool description hash verified OK');
  return true;
}
